"""Generate the synthetic test corpus under tests/fixtures/.

Everything here is invented. The topic is a fictional grid-scale sand battery
pilot in the fictional town of Vesterholm, run by the fictional Aurelia
Institute; every URL uses an RFC 2606 reserved ``.example`` domain, so nothing
can collide with a real site and nothing was ever scraped. This matters
because the repo goes public with these files committed.

Deterministic: same seed, same bytes, on every platform (all files are
written as bytes with LF endings). A unit test regenerates the corpus into a
temp dir and diffs hashes against the committed one, so drift is a test
failure.

Output:
    tests/fixtures/html/f01.html .. f40.html   the corpus
    tests/fixtures/robots/<domain>.txt          robots fixtures (one disallows)
    tests/fixtures/manifest.json                file -> url/title/kind/dup_of
    tests/fixtures/relevance.json               hand-labeled 30-chunk set
    tests/fixtures/anthropic/*.json             redacted API response shapes
    tests/fixtures/PROVENANCE.md                synthetic-origin marker
"""

from __future__ import annotations

import argparse
import json
import random
import sys
from pathlib import Path

SEED = 1207
MARKER = "SYNTHETIC-FIXTURE-CORPUS: generated by scripts/make_fixtures.py, seed 1207"

DOMAINS = {
    "news": "vesterholm-times.example",
    "journal": "thermal-storage-review.example",
    "org": "aurelia-institute.example",
    "blog": "energy-blog-nordica.example",
    "wiki": "heatbank-wiki.example",
    "wire": "gridwatch-daily.example",
    "research": "polarforsk.example",
    "vendor": "sandtech-vendor.example",
}

# The shared canon of invented facts. Some deliberately disagree.
FACTS = [
    "The Vesterholm pilot stores 8 megawatt hours of heat in 110 tonnes of quartz sand.",
    "Resistive heaters raise the sand bed to 600 degrees Celsius during off-peak hours.",
    "The Aurelia Institute reports a round-trip thermal efficiency of 85 percent.",
    "Nordica Energy Blog claims round-trip efficiency approaches 92 percent, a figure the journal disputes.",
    "Commissioning finished in March 2024 after a nine month build.",
    "District heating offtake covers 240 homes and the municipal swimming pool.",
    "Levelized storage cost is estimated at 24 euros per megawatt hour of delivered heat.",
    "Discharge runs through a closed air loop feeding a plate heat exchanger.",
    "Peak discharge power is 1.2 megawatts thermal, sustained for roughly six hours.",
    "The sand bed sits in an insulated steel silo thirteen metres tall.",
    "Sensors log bed temperature at 96 points every thirty seconds.",
    "A second 40 megawatt hour unit is planned for the Lindqvist industrial park in 2027.",
    "Charging draws exclusively on curtailed wind power from the Vesterholm fjord array.",
    "The pilot cost 1.9 million euros, of which 0.6 million was the silo and insulation.",
    "Standing losses average 0.4 percent of stored energy per day in winter conditions.",
    "The control system holds discharge air at 190 degrees Celsius for the district loop.",
    "Sand was sourced from local dredging spoil and required no washing or grading.",
    "Aurelia's monitoring paper counts 3,100 full-equivalent cycles as the design life.",
]

FILLER = [
    "Thermal storage in solid media has a long history in industrial process heat.",
    "Sand offers a wide operating temperature range and does not degrade with cycling.",
    "District heating networks make seasonal storage economics considerably simpler.",
    "Electrification of heat is widely seen as the fastest path to cutting fossil use.",
    "Round-trip figures for heat storage are not comparable with battery electric storage.",
    "Insulation thickness is the dominant lever on standing losses in small silos.",
    "Off-peak charging aligns storage operation with periods of negative power prices.",
    "The municipality holds a minority stake in the operating company.",
    "Curtailment of wind generation remains common on the northern grid in shoulder seasons.",
    "Instrumentation data is published quarterly in an open archive.",
    "Critics note that thermal storage does not return electricity to the grid.",
    "Local contractors handled civil works while the vendor supplied the heater skid.",
    "The project timeline slipped twice on heat exchanger deliveries.",
    "Community response has been broadly positive, with noise the main early complaint.",
    "Regulatory treatment of heat storage varies widely across the region.",
]

OFFTOPIC = [
    "The Vesterholm harbour festival returns in June with a record number of stalls.",
    "Migration patterns of the lesser sandpiper shifted north again this spring.",
    "The municipal library extended weekend opening hours after a successful trial.",
    "A new bakery on Havnegade has revived a century-old rye starter.",
    "The under-16 handball team reached the regional final for the first time.",
    "Ferry timetables change on the first of May for the summer season.",
]

SYNONYMS = [
    ("reports", "says"),
    ("estimated", "projected"),
    ("roughly", "about"),
    ("finished", "wrapped up"),
    ("planned", "slated"),
    ("covers", "serves"),
    ("draws", "relies"),
    ("holds", "keeps"),
    ("counts", "lists"),
    ("offers", "provides"),
]

SECTION_TITLES = [
    "Background",
    "How the pilot works",
    "Efficiency and losses",
    "Costs and financing",
    "Grid integration",
    "Community and siting",
    "What comes next",
    "Measured performance",
    "Design choices",
    "Open questions",
]


def _paragraph(rng: random.Random, facts: list[str], n_sentences: int) -> str:
    pool = facts + FILLER
    return " ".join(rng.sample(pool, k=min(n_sentences, len(pool))))


def _article_html(title: str, date: str, site: str, sections: list[tuple[str, list[str]]]) -> str:
    body = [f"<h1>{title}</h1>", f'<p class="byline">Published {date} | {site}</p>']
    for heading, paragraphs in sections:
        body.append(f"<h2>{heading}</h2>")
        body.extend(f"<p>{p}</p>" for p in paragraphs)
    nav = '<nav><a href="/">Home</a> | <a href="/about">About</a></nav>'
    footer = f"<footer><p>Contact: desk@{site}. All content fictional.</p></footer>"
    return (
        "<!DOCTYPE html>\n"
        f"<!-- {MARKER} -->\n"
        '<html lang="en"><head><meta charset="utf-8">'
        f"<title>{title}</title></head>\n"
        f"<body>{nav}\n<article>\n" + "\n".join(body) + f"\n</article>\n{footer}</body></html>\n"
    )


def _make_normal_doc(rng: random.Random, index: int) -> tuple[str, dict[str, object]]:
    kind_key = rng.choice(list(DOMAINS))
    domain = DOMAINS[kind_key]
    n_facts = rng.randint(4, 8)
    facts = rng.sample(FACTS, k=n_facts)
    title_bits = [
        "Vesterholm sand battery",
        "Sand storage pilot",
        "Aurelia heat pilot",
        "Grid-scale sand heat store",
    ]
    title = f"{rng.choice(title_bits)}: {rng.choice(SECTION_TITLES).lower()} (f{index:02d})"
    date = f"2024-{rng.randint(3, 12):02d}-{rng.randint(1, 28):02d}"
    n_sections = rng.randint(3, 5)
    sections: list[tuple[str, list[str]]] = []
    for heading in rng.sample(SECTION_TITLES, k=n_sections):
        paragraphs = [_paragraph(rng, facts, rng.randint(3, 6)) for _ in range(rng.randint(2, 3))]
        sections.append((heading, paragraphs))
    html = _article_html(title, date, domain, sections)
    slug = f"f{index:02d}-{kind_key}"
    meta = {
        "file": f"f{index:02d}.html",
        "url": f"https://{domain}/2024/{slug}",
        "title": title,
        "domain": domain,
        "kind": "normal",
        "dup_of": None,
    }
    return html, meta


def _perturb(html: str, rng: random.Random) -> str:
    """Light rewrite: synonym swaps and a shuffled date, keeping ~95 percent
    of the text identical so cosine and SimHash both flag it."""
    out = html
    for a, b in rng.sample(SYNONYMS, k=6):
        out = out.replace(a, b)
    out = out.replace("Published 2024-", "Published (updated) 2024-")
    return out


def build_corpus(out_dir: Path) -> None:
    rng = random.Random(SEED)
    html_dir = out_dir / "html"
    robots_dir = out_dir / "robots"
    anthropic_dir = out_dir / "anthropic"
    for directory in (html_dir, robots_dir, anthropic_dir):
        directory.mkdir(parents=True, exist_ok=True)

    manifest: list[dict[str, object]] = []
    docs: dict[int, str] = {}

    # f01..f30: normal articles. Six of them (f03,f08,f13,f18,f23,f28) are
    # near-duplicates of the preceding doc, wire-service style.
    dup_targets = {3: 2, 8: 7, 13: 12, 18: 17, 23: 22, 28: 27}
    for index in range(1, 31):
        if index in dup_targets:
            base_index = dup_targets[index]
            base_meta = manifest[base_index - 1]
            html = _perturb(docs[base_index], rng)
            domain = DOMAINS["wire"]
            meta = {
                "file": f"f{index:02d}.html",
                "url": f"https://{domain}/wire/f{index:02d}-syndicated",
                "title": f"{base_meta['title']} (syndicated)",
                "domain": domain,
                "kind": "near_dup",
                "dup_of": base_meta["file"],
            }
        else:
            html, meta = _make_normal_doc(rng, index)
        docs[index] = html
        manifest.append(meta)
        (html_dir / str(meta["file"])).write_bytes(html.encode("utf-8"))

    # f31..f36: normal articles from the remaining variety.
    for index in range(31, 37):
        html, meta = _make_normal_doc(rng, index)
        docs[index] = html
        manifest.append(meta)
        (html_dir / str(meta["file"])).write_bytes(html.encode("utf-8"))

    # f37: paywall stub. Almost no extractable body.
    paywall = (
        "<!DOCTYPE html>\n"
        f"<!-- {MARKER} -->\n"
        '<html><head><meta charset="utf-8"><title>Sand battery economics, part 2</title></head>'
        "<body><h1>Sand battery economics, part 2</h1>"
        '<p class="teaser">The full cost model behind the Vesterholm pilot&hellip;</p>'
        '<div class="paywall"><p>Subscribe to continue reading. Already a member? Sign in.</p>'
        "</div></body></html>\n"
    )
    (html_dir / "f37.html").write_bytes(paywall.encode("utf-8"))
    manifest.append(
        {
            "file": "f37.html",
            "url": f"https://{DOMAINS['journal']}/2024/f37-economics-part-2",
            "title": "Sand battery economics, part 2",
            "domain": DOMAINS["journal"],
            "kind": "paywall",
            "dup_of": None,
        }
    )

    # f38: JavaScript-only shell. Nothing server-rendered.
    js_only = (
        "<!DOCTYPE html>\n"
        f"<!-- {MARKER} -->\n"
        '<html><head><meta charset="utf-8"><title>Live dashboard</title></head>'
        '<body><div id="root"></div>'
        '<script>window.__APP__={"route":"/dashboard"};document.getElementById("root")'
        '.innerHTML="loading";</script></body></html>\n'
    )
    (html_dir / "f38.html").write_bytes(js_only.encode("utf-8"))
    manifest.append(
        {
            "file": "f38.html",
            "url": f"https://{DOMAINS['org']}/dashboard",
            "title": "Live dashboard",
            "domain": DOMAINS["org"],
            "kind": "js_only",
            "dup_of": None,
        }
    )

    # f39: malformed encoding. Declares utf-8 but carries latin-1 bytes and a
    # truncated multibyte sequence.
    bad_prefix = (
        "<!DOCTYPE html>\n"
        f"<!-- {MARKER} -->\n"
        '<html><head><meta charset="utf-8"><title>Temperature notes</title></head>'
        "<body><h1>Temperature notes</h1><p>"
    ).encode()
    bad_body = b"Temperatur\xe9n in the bed reached 600\xb0C during trials\xe2\x82"
    bad_suffix = (
        " and held for six hours according to the fictional log.</p>"
        "<p>" + " ".join(FILLER[:6]) + "</p></body></html>\n"
    ).encode("utf-8")
    (html_dir / "f39.html").write_bytes(bad_prefix + bad_body + bad_suffix)
    manifest.append(
        {
            "file": "f39.html",
            "url": f"https://{DOMAINS['research']}/notes/f39-temperature",
            "title": "Temperature notes",
            "domain": DOMAINS["research"],
            "kind": "bad_encoding",
            "dup_of": None,
        }
    )

    # f40: a fine article that robots.txt disallows. The fetcher must refuse it.
    html, meta = _make_normal_doc(rng, 40)
    meta["url"] = f"https://{DOMAINS['wire']}/private/f40-internal-briefing"
    meta["domain"] = DOMAINS["wire"]
    meta["kind"] = "robots_disallowed"
    (html_dir / "f40.html").write_bytes(html.encode("utf-8"))
    manifest.append(meta)

    # robots fixtures: wire domain disallows /private/, others allow all.
    for domain in DOMAINS.values():
        if domain == DOMAINS["wire"]:
            robots = "User-agent: *\nDisallow: /private/\nCrawl-delay: 1\n"
        else:
            robots = "User-agent: *\nDisallow:\n"
        (robots_dir / f"{domain}.txt").write_bytes(robots.encode("utf-8"))

    _write_json(out_dir / "manifest.json", {"marker": MARKER, "seed": SEED, "docs": manifest})
    _write_json(out_dir / "relevance.json", _relevance_set())
    for name, payload in _anthropic_shapes().items():
        _write_json(anthropic_dir / f"{name}.json", payload)

    provenance = (
        f"# Fixture provenance\n\n{MARKER}\n\n"
        "Every document in this corpus is synthetic. The topic (a sand battery\n"
        "pilot in Vesterholm run by the Aurelia Institute) and every fact,\n"
        "site, and person are invented. All URLs use RFC 2606 reserved\n"
        "`.example` domains. Nothing was fetched from the network to build\n"
        "these files, and `scripts/pre_public_audit.py` checks this marker.\n"
    )
    (out_dir / "PROVENANCE.md").write_bytes(provenance.encode("utf-8"))


def _write_json(path: Path, data: object) -> None:
    path.write_bytes((json.dumps(data, indent=2, sort_keys=True) + "\n").encode("utf-8"))


def _relevance_set() -> dict[str, object]:
    """Hand-labeled graded relevance: 30 judged chunks across 5 queries.

    Grades: 3 directly answers, 2 relevant context, 1 marginally related,
    0 irrelevant. The reranker regression test computes nDCG@6 per query and
    requires the reranked order to beat a lexical baseline.
    """
    judgments = [
        {
            "query": "What is the round-trip efficiency of the Vesterholm sand battery?",
            "chunks": [
                {"text": FACTS[2], "grade": 3},
                {"text": FACTS[3], "grade": 3},
                {"text": FACTS[14], "grade": 2},
                {"text": FILLER[4], "grade": 1},
                {"text": FACTS[5], "grade": 0},
                {"text": OFFTOPIC[0], "grade": 0},
            ],
        },
        {
            "query": "How much did the Vesterholm pilot cost to build?",
            "chunks": [
                {"text": FACTS[13], "grade": 3},
                {"text": FACTS[6], "grade": 2},
                {"text": FILLER[2], "grade": 1},
                {"text": FACTS[1], "grade": 0},
                {"text": OFFTOPIC[3], "grade": 0},
                {"text": FILLER[7], "grade": 1},
            ],
        },
        {
            "query": "How is the stored heat discharged to the district network?",
            "chunks": [
                {"text": FACTS[7], "grade": 3},
                {"text": FACTS[15], "grade": 3},
                {"text": FACTS[8], "grade": 2},
                {"text": FILLER[5], "grade": 1},
                {"text": OFFTOPIC[5], "grade": 0},
                {"text": FACTS[16], "grade": 0},
            ],
        },
        {
            "query": "Where does the electricity for charging the sand battery come from?",
            "chunks": [
                {"text": FACTS[12], "grade": 3},
                {"text": FILLER[8], "grade": 2},
                {"text": FILLER[6], "grade": 2},
                {"text": FACTS[9], "grade": 0},
                {"text": OFFTOPIC[1], "grade": 0},
                {"text": FACTS[4], "grade": 1},
            ],
        },
        {
            "query": "What are the future expansion plans for sand battery capacity?",
            "chunks": [
                {"text": FACTS[11], "grade": 3},
                {"text": FACTS[17], "grade": 2},
                {"text": FILLER[14], "grade": 1},
                {"text": OFFTOPIC[4], "grade": 0},
                {"text": FACTS[10], "grade": 0},
                {"text": FILLER[13], "grade": 1},
            ],
        },
    ]
    total = sum(len(q["chunks"]) for q in judgments)
    assert total == 30, f"relevance set must hold 30 judged chunks, got {total}"
    return {"marker": MARKER, "graded_scale": "0-3", "queries": judgments}


def _anthropic_shapes() -> dict[str, object]:
    """Recorded response shapes with fixture ids and no real identifiers."""
    plan_text = json.dumps(
        {
            "sub_questions": [
                {
                    "id": f"sq{i:02d}",
                    "question": f"Fixture sub-question {i} about the sand battery pilot?",
                    "queries": [f"vesterholm sand battery query {i}a", f"sand storage query {i}b"],
                    "success_criterion": f"Fixture criterion {i} is satisfied by cited evidence.",
                }
                for i in range(1, 10)
            ]
        }
    )
    gap_text = json.dumps(
        {
            "saturated": False,
            "assessments": [
                {"sub_question_id": "sq01", "covered": True, "missing": ""},
                {
                    "sub_question_id": "sq02",
                    "covered": False,
                    "missing": "No independent efficiency measurement found.",
                },
            ],
            "new_queries": ["vesterholm pilot independent efficiency audit"],
            "rationale": "Coverage is thin on sq02.",
        }
    )

    def message(text: str, model: str, usage: dict[str, int], suffix: str) -> dict[str, object]:
        return {
            "id": f"msg_fixture_{suffix}",
            "type": "message",
            "role": "assistant",
            "model": model,
            "content": [{"type": "text", "text": text}],
            "stop_reason": "end_turn",
            "stop_sequence": None,
            "usage": usage,
        }

    return {
        "plan_response": message(
            plan_text,
            "claude-opus-5",
            {
                "input_tokens": 812,
                "output_tokens": 1290,
                "cache_creation_input_tokens": 0,
                "cache_read_input_tokens": 0,
            },
            "plan_0001",
        ),
        "gap_response": message(
            gap_text,
            "claude-sonnet-5",
            {
                "input_tokens": 9410,
                "output_tokens": 402,
                "cache_creation_input_tokens": 0,
                "cache_read_input_tokens": 0,
            },
            "gap_0001",
        ),
        "synth_cache_write": message(
            "## Background\n\nFixture section text citing evidence [1] and [2].",
            "claude-opus-5",
            {
                "input_tokens": 220,
                "output_tokens": 640,
                "cache_creation_input_tokens": 60000,
                "cache_read_input_tokens": 0,
            },
            "synth_0001",
        ),
        "synth_cache_read": message(
            "## Efficiency\n\nFixture section text citing evidence [3].",
            "claude-opus-5",
            {
                "input_tokens": 214,
                "output_tokens": 588,
                "cache_creation_input_tokens": 0,
                "cache_read_input_tokens": 60000,
            },
            "synth_0002",
        ),
        "rate_limit_error": {
            "type": "error",
            "error": {"type": "rate_limit_error", "message": "Fixture rate limit."},
        },
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out",
        type=Path,
        default=Path(__file__).resolve().parents[1] / "tests" / "fixtures",
        help="output directory (default: tests/fixtures)",
    )
    args = parser.parse_args()
    build_corpus(args.out)
    n_files = len(list((args.out / "html").glob("*.html")))
    print(f"fixture corpus written to {args.out} ({n_files} html docs)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
