// Quarry-LDR report template: cover page, footer, typography, accent.
// Checked in and shipped with the package; report/pdf.py imports it into
// every generated report source. No remote packages: compiles offline.

#let accent = rgb("#b45309")
#let ink = rgb("#1e293b")
#let muted = rgb("#64748b")

#let quarry-report(
  title: "",
  run-id: "",
  date: "",
  engine: "",
  cost: "",
  body,
) = {
  set document(title: title)
  set text(size: 10.5pt, fill: ink)
  set par(justify: true, leading: 0.65em)
  set page(
    paper: "a4",
    margin: (x: 2.2cm, top: 2.4cm, bottom: 2.6cm),
    footer: context {
      set text(size: 8pt, fill: muted)
      line(length: 100%, stroke: 0.5pt + muted.lighten(50%))
      v(2pt)
      grid(
        columns: (1fr, auto),
        [Quarry-LDR - run #run-id],
        counter(page).display("1 / 1", both: true),
      )
    },
  )
  show heading.where(level: 2): it => {
    v(10pt)
    text(size: 15pt, weight: "bold", fill: accent)[#it.body]
    v(2pt)
    line(length: 100%, stroke: 0.75pt + accent.lighten(55%))
    v(6pt)
  }
  show heading.where(level: 3): it => {
    v(6pt)
    text(size: 12pt, weight: "semibold", fill: ink)[#it.body]
    v(3pt)
  }

  page(footer: none)[
    #v(3.2cm)
    #line(length: 34%, stroke: 2.5pt + accent)
    #v(0.9cm)
    #text(size: 26pt, weight: "bold")[#title]
    #v(0.5cm)
    #text(size: 12pt, fill: muted)[A cited research report]
    #v(1.4cm)
    #grid(
      columns: (auto, auto),
      column-gutter: 1.2cm,
      row-gutter: 0.45cm,
      text(fill: muted)[Date], text[#date],
      text(fill: muted)[Engine], text[#engine],
      text(fill: muted)[API spend], text[#cost],
      text(fill: muted)[Run id], text[#run-id],
    )
    #v(1fr)
    #text(size: 9pt, fill: muted)[Generated by Quarry-LDR - local deep research]
  ]

  body
}
